spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        topics:
          binder: kafka
          destination: topics
          content-type: application/json
          group: input-group-1


  application:
    name: kafka-elasticsearch-connector
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
  elasticsearch:
    rest:
      uris: http://localhost:9200
